//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moody.MultiResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Multi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Multi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moody.MultiResources.Multi", typeof(Multi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angry.
        /// </summary>
        public static string wAngry {
            get {
                return ResourceManager.GetString("wAngry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string wApproveBtn {
            get {
                return ResourceManager.GetString("wApproveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Boy.
        /// </summary>
        public static string wBadBoy {
            get {
                return ResourceManager.GetString("wBadBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string wBy {
            get {
                return ResourceManager.GetString("wBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string wComments {
            get {
                return ResourceManager.GetString("wComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool.
        /// </summary>
        public static string wCool {
            get {
                return ResourceManager.GetString("wCool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crazy.
        /// </summary>
        public static string wCrazy {
            get {
                return ResourceManager.GetString("wCrazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feels.
        /// </summary>
        public static string wFeels {
            get {
                return ResourceManager.GetString("wFeels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends Moods.
        /// </summary>
        public static string wFriendsMoods {
            get {
                return ResourceManager.GetString("wFriendsMoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy.
        /// </summary>
        public static string wHappy {
            get {
                return ResourceManager.GetString("wHappy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Do You Feel ?.
        /// </summary>
        public static string wHowDoYouFeel {
            get {
                return ResourceManager.GetString("wHowDoYouFeel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string wLike {
            get {
                return ResourceManager.GetString("wLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liked.
        /// </summary>
        public static string wLiked {
            get {
                return ResourceManager.GetString("wLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love.
        /// </summary>
        public static string wLove {
            get {
                return ResourceManager.GetString("wLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string wMessage {
            get {
                return ResourceManager.GetString("wMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mood Tunnel.
        /// </summary>
        public static string wMoodTunnel {
            get {
                return ResourceManager.GetString("wMoodTunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Moods.
        /// </summary>
        public static string wMyMoods {
            get {
                return ResourceManager.GetString("wMyMoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Comment.
        /// </summary>
        public static string wPostComment {
            get {
                return ResourceManager.GetString("wPostComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick.
        /// </summary>
        public static string wSick {
            get {
                return ResourceManager.GetString("wSick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surprised.
        /// </summary>
        public static string wSurprised {
            get {
                return ResourceManager.GetString("wSurprised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tired.
        /// </summary>
        public static string wTired {
            get {
                return ResourceManager.GetString("wTired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why ?.
        /// </summary>
        public static string wWhy {
            get {
                return ResourceManager.GetString("wWhy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World&apos;s Moods.
        /// </summary>
        public static string wWorldsMoods {
            get {
                return ResourceManager.GetString("wWorldsMoods", resourceCulture);
            }
        }
    }
}
